export const IPC = {
  settingsGet: "settings:get",
  settingsChooseBase: "settings:choose-base",
  settingsUpdateRate: "settings:update-rate",
  settingsSaveKey: "settings:save-key",
  settingsDeleteKey: "settings:delete-key",
  settingsTestKey: "settings:test-key",
  invoicesList: "invoices:list",
  invoicesCreate: "invoices:create",
  invoicesLoad: "invoices:load",
  invoicesRemove: "invoices:remove",
  invoicesCheck: "invoices:check",
  invoicesSetReviewAcknowledgement: "invoices:set-review-acknowledgement",
  invoicesSaveRows: "invoices:save-rows",
  receiptsChoose: "receipts:choose",
  receiptsImport: "receipts:import",
  receiptsRetry: "receipts:retry",
  rowsDelete: "rows:delete",
  rowsUndoDelete: "rows:undo-delete",
  receiptPreview: "receipt:preview",
  receiptDebug: "receipt:debug",
  invoiceCopyTsv: "invoice:copy-tsv",
  invoiceReveal: "invoice:reveal",
  invoiceBuildOutput: "invoice:build-output",
  invoiceRevealOutput: "invoice:reveal-output",
  invoiceExport: "invoice:export",
  importProgress: "import:progress",
} as const;
